### ISSUE TITLE
Plugin with elastic nodes in docker images

### ISSUE THREAD

**Issue by BhavikTanna** [ForgeRock/es-change-feed-plugin#2]
Hi I was wandering if anyone else had used this plugin within a docker image?  A brief description of my setup is:

A docker image with elasticsearch (2.3.5)
A docker image with a Golang server that dials into the plugin and listens for the changes. 

And these are made into a network via docker-compose

There are 2 of each of the above images and the elasticsearch docker images form a cluster.

If i curl in data into one of the elastic nodes, the data is always consumed and shared within the cluster (so i can see the data using the search command in a web browser on both elastics)  However, it seems that quite frequently, the plugin will not register and send out the message to my backend.  Ive rebuilt the plugin with some debug and can see when a message is sent, and seems to be skipping a few.

Do you have any idea on what could be causing this?  I'm thinking it might be a timing/timeout issue, and so was wandering if anyone had tried using this plugin within a docker image and a network using docker-compose?

Any help would be appreciated.

Thanks,

Bhavik

**Comment by jurgc11** [comment]
Hi Bhavik,

I haven't had any experience of using the plugin in Docker yet, however I'll likely be looking to Dockerise our Elasticsearch cluster this month so i'll let you know how I get on.

Chris

**Comment by BhavikTanna** [comment]
Hi Chris,

That would be really helpful.  I think it is just something to do with the time it takes to get through the docker internal network, and some of the updates are getting missed.

Cheers,

Bhavik

**Comment by BhavikTanna** [comment]
Hi Chris,

Just wanted to check if you had managed to look into the dockerisation of your elastic cluster yet?

Thanks,

Bhavik

**Comment by jurgc11** [comment]
Hi Bhavik,

It's still something I need to do, but have been sidetracked and haven't done it yet. The plan now is to look at it in a couple of weeks along with upgrading to 5.x. 

Chris

**Comment by jurgc11** [comment]
Hi Bhavik,

I don't know if this is still relevant, but I finally got round to moving our Elasticsearch stack into Docker. I haven't seen this issue, however I do have a significantly different setup to you, particularly since i'm using Docker Swarm and ES 5.4. 

A couple of things I can think of are:

- In the newer versions of the plugin (for ES 5.x) the way the plugin registers itself has changed significantly. It may be worth trying with one of these versions. 
- If you're making lots of changes, the plugin could be overwhelmed. Changing your filter setting on the plugin may help with that. 
- There are significant network issues when running Docker in vSphere. If you are using vSphere, this could be the problem.

Sorry I can't be more help.
Chris
